Repository marcusju23/vueproject-group7, pull requests merged in 2024-10, with the labels that each got.

#2 1 general cleanup
  public/.gitkeep
  public/favicon.ico
  src/App.vue
  src/assets/base.css
  src/assets/logo.svg
  src/assets/main.css
  src/assets/style.css
  src/components/Header.vue
  src/components/HelloWorld.vue
  src/components/TheWelcome.vue
  src/components/WelcomeItem.vue
  src/components/__tests__/.gitkeep
  src/components/__tests__/HelloWorld.spec.js
  src/components/icons/.gitkeep
  src/components/icons/IconCommunity.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconEcosystem.vue
  src/components/icons/IconSupport.vue
  src/components/icons/IconTooling.vue
  src/main.js
  src/router/index.js
  src/views/.gitkeep
  src/views/AboutView.vue
  src/views/HomeView.vue
Labels: enhancement

#19 Vg 33 set default server port
  vite.config.js
Labels: enhancement

#25 Vg 37 make pages more representable
  src/assets/style.css
  src/components/Navbar.vue
  src/components/ProductCard.vue
  src/views/HomeView.vue
  src/views/ProductDetailView.vue
Labels: enhancement

#29 Vg 54 display categories
  src/api/apiService.js
  src/assets/style.css
  src/views/HomeView.vue
Labels: enhancement

#27 VG-31-Routing-till-egna-API-endpoints-som-utf-r-logik-g-llande-eran-data-i-JSON-fil-GET-POST-etc-
  jsconfig.json
  package.json
  src/api/apiService.js
  src/router/server.js
Labels: enhancement

#31 VG-59-Create-a-dockerfile-to-containerize-the-back-end-server
  Dockerfile
  docker-compose.yml
  package.json
Labels: enhancement

#28 Vg 56 add searchbar to navbar and search functionality
  src/App.vue
  src/components/Navbar.vue
  src/views/HomeView.vue
  src/views/ProductDetailView.vue
Labels: enhancement

#30 Vg 35 2 add footer that is flexible with content
  src/App.vue
  src/assets/style.css
  src/components/Footer.vue
  src/components/Navbar.vue
  src/components/icons/.gitkeep
  src/components/icons/github-mark-white.png
  src/views/HomeView.vue
Labels: enhancement

#33 Vg 44 finish about page
  src/assets/images/Daniel.png
  src/assets/images/Dennis.png
  src/assets/images/Marcus.png
  src/assets/images/Rishad.png
  src/views/AboutView.vue
Labels: enhancement

#34 Vg 55 improve navigation
  src/assets/style.css
  src/components/Footer.vue
  src/components/Navbar.vue
  src/components/icons/hamburger.png
  src/components/icons/home-icon.png
  src/views/AboutView.vue
Labels: enhancement

#36 Vg 43 finish contact page
  src/views/ContactView.vue
Labels: enhancement

#35 Vg 60 fix size scaling
  src/App.vue
  src/router/index.js
  src/views/AboutView.vue
  src/views/HomeView.vue
  src/views/ProductDetailView.vue
Labels: enhancement

#38 Vg 57 add suggested products in detail page
  src/views/ContactView.vue
  src/views/ProductDetailView.vue
Labels: enhancement

#37 Vg 39 add cart to navbar and expense tracker functionality
  src/App.vue
  src/assets/style.css
  src/components/Navbar.vue
  src/components/ProductCard.vue
  src/components/icons/shopping-cart.png
  src/store/store.js
  src/views/ProductDetailView.vue
  tailwind.config.js
Labels: enhancement, requirement

#40 VG-67-Create-a-database-that-stores-ordered-products
  docker-compose.yml
  package.json
  src/router/server.js
Labels: enhancement

#41 Vg 75 cart improvements
  src/components/Navbar.vue
  src/store/store.js
  src/views/ProductDetailView.vue
Labels: enhancement

#42 Vg 20 implement testing
  .github/workflows/pipeline.yml
  README.md
  package.json
  src/components/__tests__/.gitkeep
  src/components/__tests__/App.spec.js
  src/components/__tests__/Navbar.spec.js
  src/components/__tests__/ProductCard.spec.js
  src/components/__tests__/store.spec.js
Labels: enhancement

#44 VG-66-Update-documentation
  README.md
Labels: documentation

#43 Vg 19 run tests on startup
  package.json
Labels: enhancement

#45 VG-63 Styling for product pages
  src/views/ProductDetailView.vue
Labels: enhancement
